version: '3'

services:
  api:
    build: .
    command: npm run dev
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - HOST=localhost
      - MONGO_URL=mongodb://api_db:27017/api
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api:
