name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (Clone repository)
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          chmod 600 ssh_key

      - name: Upload project to server
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}

      - name: Deploy with Docker
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ${{ secrets.PROJECT_PATH }}
          docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} down
          docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} pull
          docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} build
          docker-compose -f ${{ secrets.DOCKER_COMPOSE_FILE }} up -d
          EOF
