name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository (Clone repository)
        uses: actions/checkout@v3

      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH Key
        run: |
          chmod 600 ssh_key

      - name: Deploy to Windows Server
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            powershell -Command '
              cd "D:\Projects\HelloDockerRealWorld"
              echo "CD ..."
            '
          "

  
