name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository (Clone repository)
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Windows server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
              cd ''D:/Training projects/hello-docker-real-world'';
              git pull origin main;
              docker-compose down;
              docker-compose up -d --build
          "
